name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
<<<<<<< HEAD
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          channelId: live
          projectId: tripdarzee1303
=======
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT}}
          channelId: live
          projectId: tripdarzee1303
>>>>>>> 699ed7100ed564c9781be5ef057dcbdc5d369167
